# Generated by Django 6.0.2 on 2026-02-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate', 'CAC Certificate'), ('status_report', 'Status Report'), ('memart', 'MEMART'), ('name_approval', 'Name Approval Document')], max_length=50)),
                ('file', models.FileField(upload_to='registration_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registrations.registration')),
            ],
        ),
    ]
