# Generated by Django 6.0.2 on 2026-02-24 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('certificate', 'CAC Certificate'), ('status_report', 'Status Report'), ('memart', 'MEMART'), ('name_approval', 'Name Approval Document'), ('supporting_doc', 'Supporting Document'), ('correction_doc', 'Correction Document')], max_length=50),
        ),
    ]
