# Generated by Django 6.0.2 on 2026-02-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
