# Generated by Django 6.0.2 on 2026-02-13 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('business_name', 'Business Name'), ('ltd', 'Private Limited Company')], max_length=20)),
                ('name_option_1', models.CharField(max_length=255)),
                ('name_option_2', models.CharField(max_length=255)),
                ('approved_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('queried', 'Queried'), ('responded', 'User Responded'), ('name_approved', 'Name Approved'), ('name_denied', 'Name Denied'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
