# Generated by Django 6.0.2 on 2026-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
