# Generated by Django 6.0.2 on 2026-02-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='query_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
